### ISSUE TITLE
Research Google's CustomSearch API 

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/BCPL-assets#498]
@danfox01 assigning to you, so you can get me the information we talked about.

**Comment by danfox01** [comment]
Our Swiftype contract is up in October, so I'd like to explore the feasibility of switching to this at that time. The API allows 100 queries per day for free, so that should be more than enough for testing. I can share the Google API key with you offline.

Main questions for you:
- What is the level of effort to switch BCG and BCPL sites from Swiftype to Google CSE API?
- Is it possible to use the existing Google CSE autocomplete (non-API) to provide suggestions in the search bar, but serve search results via the API. Let me know if you need more explanation on this.

**Comment by martypowell** [comment]
@danfox01 I need more explanation on last bullet, but the rest is clear.

**Comment by martypowell** [comment]
Remaining Tasks

- Get Autocomplete integrated into the template (includes styling)
- Look into mobile version of paging
- Merge new code into service
- Ensure we can flip between providers

**Comment by martypowell** [comment]
@danfox01 marking this is blocked until we are ready to move forward with this.

**Comment by martypowell** [comment]
@danfox01 closing and creating a new issue for hte implementation.
