### ISSUE TITLE
When adding new items of the Locations page, Libanswers contact forms don't render

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/BCPL-assets#616]
When adding net-new locations to the locations page, the "Contact" button does not spawn a Libanswers modal like it should.

https://www.bcpl.info/locations/index.html

**Comment by martypowell** [comment]
@tmccoy529 this can be recreated in dev. look for branches "mobile engagement" adult and "mobile engagement youth"

**Comment by martypowell** [comment]
**Expected Behavior**

1. Select "Contact Arbutus"
1. A modal should appear displaying a contact form.

**Bug Behavior**

1. Select either "mobile engagement" contact button
1. You will it appears that nothing happens apart from maybe a chance in the window location on your screen

We will need to add a readme in the bcpl wiki for adding and removing branches.

**Comment by danfox01** [comment]
@tmccoy529, @martypowell -- Is it possible to get this update in dev today so I can do some quick testing?

**Comment by martypowell** [comment]
yes, ill dump it in. fyi @tmccoy529

**Comment by martypowell** [comment]
@danfox01 @tmccoy529 this has been published to dev.

**Comment by danfox01** [comment]
Testing revealed that contact form modals on this page don't render in IE11. This affects this update in dev **and** the current prod version. @tmccoy529 just let me know if you need a separate issue opened for this, but I'd like to get this resolved for tomorrow's release.

@jdomasky recalls this issue being fixed in the past so this may have been a regression in a previous release.

**Comment by tmccoy529** [comment]
Dan,

Marty and I looked into it and we found the issue. Will push back out. Hope we can still make todays push.

Tim

**Comment by tmccoy529** [comment]
Correction, what we thought was the issue turns out to be the start of a chain of issues related exclusively to IE 11. Looking into it further we realized this actually isn't working in Prod either so this may have never worked. We should probably make this its own issue at this point since this is already out in prod this way.

**Comment by danfox01** [comment]
No problem: https://github.com/baltimorecounty/BCPL-assets/issues/621

**Comment by danfox01** [comment]
@tmccoy529 since we know the IE11 issue is independent of this one, is it possible to still release this change as a HF today? That way we can get the customer's original issue wrapped up while we're working in the IE11 bug.

**Comment by tmccoy529** [comment]
@danfox01 I think this would be ideal as the IE issue already exists in Prod so we wouldn't be pushing out a new bug with this fix.

@martypowell if you have time can you walk me through pushing a hot fix out for this?

**Comment by danfox01** [comment]
Thanks guys! Looks great. I will close this issue when we confirm the prod deployment tomorrow.

**Comment by danfox01** [comment]
This was successfully release to prod. Thanks all!
